name: weather_jan
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# Основные иконки
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.3.0 

  # Code generation
  json_annotation: ^4.9.0

  # Date/Time formatting
  intl: ^0.20.2

  # Icons
  font_awesome_flutter: ^10.8.0

  # Geolocation
  geolocator: ^13.0.2

  # Добавим полезные пакеты
  flutter_svg: ^2.0.17  # Для работы с SVG иконками
  equatable: ^2.0.7    # Для удобного сравнения объектов
  dartz: ^0.10.1       # Для функционального программирования (Option, Either)
  logger: ^2.5.0       # Для красивых логов вместо print
  flutter_dotenv: ^5.2.1 # Для хранения API ключей (очень полезно!)

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation tools
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

  # Линтеры
  flutter_lints: ^5.0.0

  # Добавим анализатор кода
  very_good_analysis: ^7.0.0  # Альтернатива flutter_lints, очень строгий анализ

flutter:
  uses-material-design: true

  assets:
     - images/weather_forecast.jpg
     - images/gori_solntse.jpg
     - images/nebo.jpg
    #  - .env  # Файл с API ключами
 
flutter_intl:
  enabled: true
